---
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35623464633039316132366561636336326461306633376164306630633663333166323930666632
          3861613064323436393235396531363662353764313035360a356633346265663366626163393365
          36323332383833373666656366336464376261643333326162616130303335626363613563303537
          6435373166336233630a623834643732306661306466313261393261623734623436363864646135
          3031

all_tailscale_login_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32373466626632356237373334646633643535316136616538343163383432613862636366353133
          3236333130643235376464356165353130323366646166320a373232643235613838313133323837
          30393238666238336464376332633166613762366137353939306134303633663538303632613235
          3136356661623932360a303262376165663761323033336439373838636365356238316233343365
          39643639643935343062353637623433633933396432343131626337353964363235

all_zsh_includes:
  - base
  - aliases
