---
common_gui_editor: visual-studio-code-bin

pacman_packages: 
  - firefox
  - spotify-player
  - fzf
  - ripgrep
  - fd
  - bat
  - btop
  - lazygit
  - tmux
  - tealdeer
  - zoxide
  - bitwarden
  - kitty
  - eza
  - zsh

aur_packages:
  - discord-canary