---
timeout_command: gtimeout

cask_packages:
  - firefox
  - discord
  - vlc
  - kitty


brew_packages:
  - spotify_player
  - fzf
  - ripgrep
  - fd
  - bat
  - btop
  - lazygit
  - tmux
  - tealdeer
  - zoxide
