---
tailscale_auth_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62386133663732313937393963623462373838633865393131643933613365303063336636386162
          3463353564396163313130386132386531653963353030640a663839653038326431383463353636
          39303761313465643261626562616437613066373134343530636466306530306330393137346530
          3364373963336561320a326432643738393564326132653464326264613834316161613863396139
          34663539643139656132393335356135613030383261316539393331303136313963643561313164
          62653062393163373537666637366137316561316237306562626663313530616163643438316230
          633537333132646435346363383935646139
