---
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35623464633039316132366561636336326461306633376164306630633663333166323930666632
          3861613064323436393235396531363662353764313035360a356633346265663366626163393365
          36323332383833373666656366336464376261643333326162616130303335626363613563303537
          6435373166336233630a623834643732306661306466313261393261623734623436363864646135
          3031
