# SPDX-License-Identifier: MIT-0
---
# tasks file for tailscale_server

# Start Tailscale with Preauth Key
- name: Tailscale Up with Preauth Key
  ansible.builtin.command: >
    tailscale up
    --authkey={{  tailscale_auth_key }}
    --login-server={{ all_tailscale_login_url }}
    --accept-routes
    --accept-dns
  changed_when: false
