---
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63393535333231393430653536333763393432363063343664346537326263373936306337646432
          6538613934383135643133623663356433356363346366320a343337336561636530623138663466
          31353835663832646633383230353136373633613033326364636539353536303066333661323932
          6239353232656635650a363764636562623534663064306338373266643266303563366636306162
          34666639623165636632366433313630313635643931633338383161313762623230

ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63393535333231393430653536333763393432363063343664346537326263373936306337646432
          6538613934383135643133623663356433356363346366320a343337336561636530623138663466
          31353835663832646633383230353136373633613033326364636539353536303066333661323932
          6239353232656635650a363764636562623534663064306338373266643266303563366636306162
          34666639623165636632366433313630313635643931633338383161313762623230
