---
open_ports:
  - {port: '22', proto: 'tcp'}
  - {port: '53', proto: 'tcp'}
  - {port: '53', proto: 'udp'}
  - {port: '80', proto: 'tcp'}
  - {port: '443', proto: 'tcp'}
  - {port: '443', proto: 'udp'}
  - {port: '8080', proto: 'tcp'}
  - {port: '8080', proto: 'udp'}
  - {port: '8081', proto: 'tcp'}
  - {port: '8081', proto: 'udp'}
